config:
- mysqlHost: tcp(sql12.freemysqlhosting.net:3306)
  mysqlUser: sql12356650
  mysqlPwd: gbk6pWFWmb
  mysqlDb: sql12356650
  # mongoHost: localhost:27017
  # mongUser: root
  # mongoPwd: ''
  # mongoDb: admin
  baseUrl: https://backendskripsi.herokuapp.com
  ipAddress: ::1
  sessionName: admin_starter
  sessionKey: admin_starter_123
  # portHost: 8081
  env: dev
  jwtName: token
  jwtKey: token

  domainMailgun: mailgun.bandros.co.id
  keyMailgun: key-a1af1fcc875f69d3d8a75b8e58231e79
  publicKeyMailgun: key-a1af1fcc875f69d3d8a75b8e58231e79
  mailSenderMailgun : noreply+waitinglist_vendor@bandros.co.id

